### ISSUE TITLE
Search - Needs to function better. Explanation below.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Community-Living-Sarnia#13]
I searched "passport" and no results came up.
I search "become a member" .. no results.
I search "job" .. no results.

These are all important parts of this website and something users would specifically search for.

**Comment by ccmorris** [comment]
I made a whole bunch of changes to the search which appears to have made a marked improvement:

- added the content in advanced pages, it was missing from the index
- ignored irrelevant words like "a" and "or"
- added a search keywords field for basic pages and advanced pages so that you can customize the keywords without changing the text content of the page. for example, you want the "careers" page to show up when you search "job"
- boosted the importance for the words in page titles and in search keywords so that the most relevant pages should be at the top of search results
- removed the author username and created date from search results pages
